
name: Build and Unit Test

on:
  push:
    branches:
      - 'main'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Requirements
      run: sudo apt-get install -y clang-11 libc++-11-dev libc++abi-11-dev
      
    - name: Checkout tuple
      uses: actions/checkout@v2
      with:
        repository: cpp-core/tuple
        path: tuple
        
    - name: Checkout depends
      uses: actions/checkout@v2
      with:
        repository: cpp-core/depends
        ref: main
        path: depends
        
    - name: Build dependencies
      run: |
        export CC=clang-11
        export CXX=clang++-11
        mkdir -p depends/build && pushd depends/build
        cmake -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/opt ..
        make mp googletest
        popd

    - name: Build and run the tests
      run: |
        export CC=clang-11
        export CXX=clang++-11
        mkdir -p tuple/build && pushd tuple/build
        cmake -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/opt ..
        make
        make check
        make install
        popd
