
name: Docs

on:
  push:
    branches:
      - 'main'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Requirements
      run: sudo apt-get install -y doxygen
      
    - name: Python Requirements
      run: pip3 install sphinx sphinx_rtd_theme breathe myst_parser
      
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Create build directory
      run: mkdir build
      
    - name: CMake configuration
      run: cd build && cmake ../docs
      
    - name: Build documentation
      run: cd build && make cxx_core_tuple_docs

    - name: Deploy documentation
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build/docs/html
        
